name: Build & Deploy hello_world_docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello_world_docker:latest ./backend

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello_world_docker:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hello_world_docker:latest
            if [ $(docker ps -q -f name=hello_world_docker) ]; then
              docker stop hello_world_docker
              docker rm hello_world_docker
            fi
            
            PORT_CONTAINER=$(docker ps -q -f publish=80)
             if [ ! -z "$PORT_CONTAINER" ]; then
             docker stop $PORT_CONTAINER
              docker rm $PORT_CONTAINER
             fi
            docker run -d --name hello_world_docker -p 80:5000 ${{ secrets.DOCKERHUB_USERNAME }}/hello_world_docker:latest


